concurrency:
  cancel-in-progress: true
  group: build-${{ github.event.pull_request.number || github.ref }}
jobs:
  build:
    name: Build debug, Jacoco test and publish to codacy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assembledebug
    - continue-on-error: true
      name: Run test cases
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: jacocoTestPlayDebugUnitTestReport
    - continue-on-error: true
      name: Publish test cases
      run: 'export CODACY_PROJECT_TOKEN=${{ secrets.CODACY_TOKEN }}

        bash <(curl -Ls https://coverage.codacy.com/get.sh)

        '
    - continue-on-error: true
      name: Publish on Telegram
      run: 'COMMIT_COUNT=$(git rev-list --count ${GITHUB_REF})

        VERSION_NAME=$(echo ${GITHUB_REF##*/} | sed ''s/release\///'' | sed ''s/hotfix\///'')

        cp app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk app/build/outputs/apk/fdroid/debug/amaze-fdroid-$(echo
        $VERSION_NAME)-$(echo $COMMIT_COUNT).apk

        cp app/build/outputs/apk/play/debug/app-play-debug.apk app/build/outputs/apk/play/debug/amaze-play-$(echo
        $VERSION_NAME)-$(echo $COMMIT_COUNT).apk

        echo $(curl -v -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -F document=@app/build/outputs/apk/fdroid/debug/amaze-fdroid-$(echo
        $VERSION_NAME)-$(echo $COMMIT_COUNT).apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID
        }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument)

        echo $(curl -v -F "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" -F document=@app/build/outputs/apk/play/debug/amaze-play-$(echo
        $VERSION_NAME)-$(echo $COMMIT_COUNT).apk https://api.telegram.org/${{ secrets.AMAZE_BOT_ID
        }}:${{ secrets.TELEGRAM_INTEGRATION_KEY }}/sendDocument)

        '
  check_spotless:
    name: Check spotless
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Check formatting using spotless
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: spotlessCheck
  test_emulator:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: checkout
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Java 15
      uses: actions/setup-java@v4
      with:
        java-version: 15
    - continue-on-error: true
      name: Gradle cache
      uses: gradle/actions/setup-gradle@v3
    - continue-on-error: true
      id: avd-cache
      name: AVD cache
      uses: actions/cache@v4
      with:
        key: avd-${{ matrix.api-level }}
        path: '~/.android/avd/*

          ~/.android/adb*

          ~/.android/debug.keystore

          '
    - continue-on-error: true
      if: steps.avd-cache.outputs.cache-hit != 'true'
      name: create AVD and generate snapshot for caching
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86
        channel: canary
        disable-animations: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          -camera-back none
        force-avd-creation: false
        ram-size: 2048M
        script: echo "Generated AVD snapshot for caching."
        sdcard-path-or-size: 100M
    - continue-on-error: true
      name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        arch: x86
        channel: canary
        disable-animations: true
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio
          -no-boot-anim -camera-back none
        force-avd-creation: false
        ram-size: 2048M
        script: 'adb logcat -c

          adb logcat *:E &

          ./gradlew :app:connectedCheck

          '
        sdcard-path-or-size: 100M
    strategy:
      fail-fast: true
      matrix:
        api-level:
        - 16
        - 19
        - 28
    timeout-minutes: 30
name: Android Main CI
on:
  repository_dispatch:
    types: trigger-ga___android-main.yml
