jobs:
  apk:
    if: github.event.comment.body == 'Build test apk' && (github.actor == 'VishalNehra'
      || github.actor == 'TranceLove' || github.actor == 'EmmanuelMess' || github.actor
      == 'VishnuSanal')
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Acknowledge the request with thumbs up reaction
      uses: peter-evans/create-or-update-comment@v2
      with:
        comment-id: ${{ github.event.comment.id }}
        reactions: '+1'
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: request
      name: Github API Request
      uses: octokit/request-action@v2.0.2
      with:
        route: ${{ github.event.issue.pull_request.url }}
    - continue-on-error: true
      id: pr_data
      name: Get PR informations
      run: 'echo "::set-output name=repo_name::${{ fromJson(steps.request.outputs.data).head.repo.full_name
        }}"

        echo "::set-output name=repo_clone_url::${{ fromJson(steps.request.outputs.data).head.repo.clone_url
        }}"

        echo "::set-output name=repo_ssh_url::${{ fromJson(steps.request.outputs.data).head.repo.ssh_url
        }}"

        '
    - continue-on-error: true
      name: Checkout PR Branch
      uses: actions/checkout@v4
      with:
        ref: ${{fromJson(steps.request.outputs.data).head.ref}}
        repository: ${{fromJson(steps.request.outputs.data).head.repo.full_name}}
        token: ${{ secrets.GITHUB_TOKEN }}
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 11
    - continue-on-error: true
      name: Build with Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        arguments: assembleDebug --stacktrace
    - continue-on-error: true
      name: Upload fdroid artifact
      uses: actions/upload-artifact@v4
      with:
        name: Amaze-Fdroid-debug
        path: app/build/outputs/apk/fdroid/debug/app-fdroid-debug.apk
    - continue-on-error: true
      name: Upload play artifact
      uses: actions/upload-artifact@v4
      with:
        name: Amaze-Play-debug
        path: app/build/outputs/apk/play/debug/app-play-debug.apk
    - continue-on-error: true
      name: Notify the user with a comment once the APK is uploaded
      uses: peter-evans/create-or-update-comment@v2
      with:
        body: 'The requested APKs has been built. Please find them from the artifacts
          section of this PR.

          '
        issue-number: ${{ github.event.issue.number }}
name: Android Debug artifact ondemand
on:
  repository_dispatch:
    types: trigger-ga___android-debug-artifact-ondemand.yml
